### ISSUE TITLE
ServiceInstanceController endpoints are failing under MySQL 5.7

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#198]
**Problem:** ServiceInstanceController includes the following endpoints:

- /serviceInstances/{id}/nodeSummary
- /serviceInstances/{id}/healthBreakdown
- /serviceInstances/{id}/rotationBreakdown

The handlers invoke ServiceInstanceRepoImpl, which includes custom JDBC code to load the requested data.

Prior to MySQL 5.7, this works fine. The reason is that the default `sql_mode`, at least for 5.6.22-log, does not include `ONLY_FULL_GROUP_BY`. However as of MySQL 5.7, the default `sql_mode` does include this value, which breaks the three SQL queries corresponding to the endpoints above.

This is impacting the service instance details page in the UI. The data doesn't load up.

**Acceptance criteria:** We need to fix this so that the queries work under MySQL, since I don't want to lock us into MySQL 5.6.

**Technical approach:** There are multiple possible approaches:

- Require MySQL 5.6. Like I said I don't like this one.
- Set the `sql_mode` in such a way as to avoid the error.
- Adjust the SQL queries (including the appropriate columns in the `GROUP_BY` clause) to make them compatible with the default `sql_mode`.
- Replace the JDBC/SQL with JPA and/or Spring Data JPA.

My preference is for the last since it's the most portable.

**Comment by williewheeler** [comment]
By the way, this change is related to #118, just because the same queries are involved. So if we end up changing the queries here, we should try to fix #118 at the same time.

**Comment by williewheeler** [comment]
See also

http://stackoverflow.com/questions/7298551/get-and-set-database-server-connection-variable-with-jdbc

**Comment by launchcg-ztonia** [comment]
My investigations suggest that the issue is not present in the current build as a symptom of the sql_mode, but rather the xml marshaler is a default feature in the 'Resource' data object class which wraps the healthBreakdown and rotationBreakdown.

The constituent data objects are not configured to render as XML, resulting in error.

**Comment by williewheeler** [comment]
Thanks Zaal--I will double-check on my machine to see if I can reproduce the SQL query errors.

**Comment by williewheeler** [comment]
I am able to reproduce this. And it is clearly a query issue, not a marshaller issue:

~~~
2016-04-19 08:43:25.531 ERROR 49949 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [select   count(*) num_nodes,   sum(healthy) num_healthy,   sum(nip_enabled * all_endpoints_enabled) num_enabled,   sum(healthy * nip_enabled * all_endpoints_enabled) num_healthy_given_enabled from (   select     if(st.ukey in ('success', 'info'), 1, 0) healthy,     if(sum(case nip_rs.ukey when 'enabled' then 0 else 1 end) = 0, 1, 0) nip_enabled,     if(sum(case e_rs.ukey when 'enabled' then 0 else 1 end) = 0, 1, 0) all_endpoints_enabled   from     node n     left outer join health_status hs on n.health_status_id = hs.id     left outer join status_type st on hs.status_type_id = st.id     left outer join node_ip_address nip on nip.node_id = n.id     left outer join rotation_status nip_rs on nip_rs.id = nip.rotation_status_id     left outer join endpoint e on e.node_ip_address_id = nip.id     left outer join rotation_status e_rs on e_rs.id = e.rotation_status_id,     service_instance si   where     n.service_instance_id = si.id     and si.id = ?   group by     nip.id) nip_stats]; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'seiso.st.ukey' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by] with root cause

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'seiso.st.ukey' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_74]
	at sun.reflect.NatiructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_74]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_74]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_74]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404) ~[mysql-connector-java-5.1.38.jar:5.1.38]
	at com.mysql.jdbc.Util.getInstance(Util.java:387) ~[mysql-connector-java-5.1.38.jar:5.1.38]
~~~
