### ISSUE TITLE
ServiceInstancePortListener generates NullPointerException after PUTting a port

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#30]
java.lang.NullPointerException: null
        at com.expedia.seiso.domain.entity.listener.ServiceInstancePortListener.postPersist(ServiceInstancePortListener.java:49)
        at sun.reflect.GeneratedMethodAccessor310.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.hibernate.jpa.event.internal.jpa.ListenerCallback.performCallback(ListenerCallback.java:49)
        at org.hibernate.jpa.event.internal.jpa.CallbackRegistryImpl.callback(CallbackRegistryImpl.java:112)
        at org.hibernate.jpa.event.internal.jpa.CallbackRegistryImpl.postCreate(CallbackRegistryImpl.java:71)
        [snip]

**Comment by williewheeler** [comment]
Fixed by b312692e9a84f337701c457d8aa907536080949f.
