### ISSUE TITLE
Changing node IP address leads to conflicts

### ISSUE THREAD

**Issue by williewheeler** [ExpediaDotCom/seiso#45]
If the user changes a node IP address in a nodes.json file, Seiso doesn't notice, and instead there is a conflict since there can't be two IP addresses for a single <node, ipAddress> pair.

Current workaround is to delete the service instance and reimport it, but we shouldn't have to do this.

**Comment by williewheeler** [comment]
Error looks like this:

    Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '243-686' for key 'node_id_ip_address_role_id'
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
        at com.mysql.jdbc.Util.getInstance(Util.java:360)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:971)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
        atsql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)

        ... snip ...

**Comment by williewheeler** [comment]
It looks like the right fix for this is to start implementing the stale data cleanup. The approach is as follows:

1. Importer queries Seiso for a node's current IP addresses.
2. Importer compares the list to its own IP addresses, and tells Seiso to delete any that aren't in its list.
3. Importer imports its list of IP addresses.

But step 3 needs to create the IP addresses if they don't already exist, rather than depending on the current JPA listener mechanism.

**Comment by williewheeler** [comment]
Done
